Adds sections for advertising and recruiting to CoC
engmanagers/engmanagers.github.io pull request #12
Opened 2018-09-24 15:07 UTC by stebennett

As a result of conversations with members around advertising and recruitment, the admins for the Slack team have decided that it is important to have clarity on our position. 

This change adds wording to the code of conduct to explain our position explaining the consequences of breaching these rules.

2018-09-24 15:14 UTC, ichthyos requested changes
Looks pretty good overall, with just a few nits to pick.

2018-09-24 15:14 UTC, ichthyos commented on _posts/2015-03-03-codeofconduct.md
> +EMS is run by a team of dedicated admins for the enjoyment and benefit of it's members. Our Admins give up their own time to foster and develop the community and as such we aim to keep the community
minor nits:
- it's -> its
- Admins -> admins
- advertising free -> advertising-free
- foul -> afoul

2018-09-24 15:14 UTC, ichthyos commented on _posts/2015-03-03-codeofconduct.md
> +We encourage members to share open job postings and we have a #jobs channel specifically for this purpose. Re-posting across multiple channels, or requesting re-posts in private channels is actively
nit: member to member -> member-to-member

2018-09-24 18:46 UTC, stebennett commented
Minor nit-picks welcome. Updated.

2018-09-26 10:34 UTC, catehstn commented
LGTM, thanks @stebennett

2018-09-26 22:58 UTC, ichthyos approved these changes
LGTM. Thanks for making these changes!

2018-09-26 22:58 UTC, ichthyos commented on _posts/2015-03-03-codeofconduct.md
> +EMS is run by a team of dedicated admins for the enjoyment and benefit of it's members. Our Admins give up their own time to foster and develop the community and as such we aim to keep the community
also, persistant -> persistent

2018-10-10 07:50 UTC, merged